# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 804)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background: rgb(40, 40, 40);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"background-color: rgb(80, 80, 80);\n"
"}\n"
"QGroupBox::title{\n"
"color: rgb(220, 220, 220)\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.collection_display = QtWidgets.QTreeWidget(self.groupBox)
        self.collection_display.setStyleSheet("QTreeWidget{\n"
"background: rgb(120, 120, 120)\n"
"}")
        self.collection_display.setHeaderHidden(True)
        self.collection_display.setObjectName("collection_display")
        self.collection_display.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.collection_display)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"   background: rgb(80, 80, 80);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: rgb(80, 80, 80);\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: rgb(80, 80, 80);\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    title-color: rgb(220, 220, 220);\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab::title {\n"
"    color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"\n"
"QTabBar::tab::selected {\n"
"    background: rgb(100, 100, 100);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.ingest_ctrls = QtWidgets.QWidget()
        self.ingest_ctrls.setMinimumSize(QtCore.QSize(411, 0))
        self.ingest_ctrls.setStyleSheet("QWidget{\n"
"    background: rgb(80, 80, 80)\n"
"}")
        self.ingest_ctrls.setObjectName("ingest_ctrls")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ingest_ctrls)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.target_url_label = QtWidgets.QLabel(self.ingest_ctrls)
        self.target_url_label.setStyleSheet("QLabel{\n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.target_url_label.setObjectName("target_url_label")
        self.horizontalLayout.addWidget(self.target_url_label)
        self.target_url = QtWidgets.QLineEdit(self.ingest_ctrls)
        self.target_url.setStyleSheet("QLineEdit{\n"
"    color: rgb(220, 220, 220)\n"
"}")
        self.target_url.setObjectName("target_url")
        self.horizontalLayout.addWidget(self.target_url)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.target_url_label_2 = QtWidgets.QLabel(self.ingest_ctrls)
        self.target_url_label_2.setStyleSheet("QLabel{\n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.target_url_label_2.setObjectName("target_url_label_2")
        self.horizontalLayout_6.addWidget(self.target_url_label_2)
        self.target_db_col = QtWidgets.QLineEdit(self.ingest_ctrls)
        self.target_db_col.setStyleSheet("QLineEdit{\n"
"    color: rgb(220, 220, 220)\n"
"}")
        self.target_db_col.setObjectName("target_db_col")
        self.horizontalLayout_6.addWidget(self.target_db_col)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Ingest_mode = QtWidgets.QComboBox(self.ingest_ctrls)
        self.Ingest_mode.setStyleSheet("QComboBox{\n"
"color: rgb(220, 220, 220);\n"
"background: rgb(120, 120, 120)\n"
"}")
        self.Ingest_mode.setObjectName("Ingest_mode")
        self.horizontalLayout_5.addWidget(self.Ingest_mode)
        self.ignore_name_check = QtWidgets.QCheckBox(self.ingest_ctrls)
        self.ignore_name_check.setStyleSheet("QCheckBox{\n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.ignore_name_check.setObjectName("ignore_name_check")
        self.horizontalLayout_5.addWidget(self.ignore_name_check)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.collection_number_label = QtWidgets.QLabel(self.ingest_ctrls)
        self.collection_number_label.setStyleSheet("QLabel{\n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.collection_number_label.setObjectName("collection_number_label")
        self.horizontalLayout_2.addWidget(self.collection_number_label)
        self.number_to_collect = QtWidgets.QSpinBox(self.ingest_ctrls)
        self.number_to_collect.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.number_to_collect.setStyleSheet("QSpinBox{\n"
"    color: rgb(220, 220, 220);\n"
"    background: rgb(120, 120, 120);\n"
"}\n"
"")
        self.number_to_collect.setMaximum(9999)
        self.number_to_collect.setObjectName("number_to_collect")
        self.horizontalLayout_2.addWidget(self.number_to_collect)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.add_to_data_base = QtWidgets.QCheckBox(self.ingest_ctrls)
        self.add_to_data_base.setStyleSheet("QCheckBox{\n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.add_to_data_base.setObjectName("add_to_data_base")
        self.horizontalLayout_2.addWidget(self.add_to_data_base)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.ingest_ctrls)
        self.label.setStyleSheet("QLabel{\n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.ingest_ctrls)
        self.spinBox.setStyleSheet("QSpinBox{\n"
"    color: rgb(220, 220, 220);\n"
"    background: rgb(120, 120, 120);\n"
"}\n"
"")
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.ingest_ctrls)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"background-color: rgb(80, 80, 80);\n"
"}\n"
"QGroupBox::title{\n"
"color: rgb(220, 220, 220)\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.console_output = QtWidgets.QTextBrowser(self.groupBox_2)
        self.console_output.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.console_output.setStyleSheet("QTextBrowser{\n"
"    color: rgb(200, 200, 200);\n"
"    background: rgb(30, 30, 30);\n"
"}")
        self.console_output.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.console_output.setOverwriteMode(False)
        self.console_output.setTabStopWidth(90)
        self.console_output.setTabStopDistance(90.0)
        self.console_output.setCursorWidth(1)
        self.console_output.setObjectName("console_output")
        self.verticalLayout_3.addWidget(self.console_output)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chkbx_debug_mode = QtWidgets.QCheckBox(self.ingest_ctrls)
        self.chkbx_debug_mode.setObjectName("chkbx_debug_mode")
        self.horizontalLayout_4.addWidget(self.chkbx_debug_mode)
        self.clear_output = QtWidgets.QPushButton(self.ingest_ctrls)
        self.clear_output.setStyleSheet("QPushButton{\n"
"    color: rgb(220, 220, 220);\n"
"    background: rgb(100, 100, 100);\n"
"}")
        self.clear_output.setObjectName("clear_output")
        self.horizontalLayout_4.addWidget(self.clear_output)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.start_collection = QtWidgets.QPushButton(self.ingest_ctrls)
        self.start_collection.setMinimumSize(QtCore.QSize(0, 60))
        self.start_collection.setStyleSheet("QPushButton{\n"
"    color: rgb(220, 220, 220);\n"
"    background: rgb(100, 100, 100);\n"
"}")
        self.start_collection.setObjectName("start_collection")
        self.verticalLayout_2.addWidget(self.start_collection)
        self.tabWidget.addTab(self.ingest_ctrls, "")
        self.data_info = QtWidgets.QWidget()
        self.data_info.setStyleSheet("QWidget{\n"
"    background: rgb(80, 80, 80)\n"
"}")
        self.data_info.setObjectName("data_info")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.data_info)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_load_collection = QtWidgets.QPushButton(self.data_info)
        self.btn_load_collection.setMinimumSize(QtCore.QSize(160, 50))
        self.btn_load_collection.setStyleSheet("QPushButton{\n"
"    color: rgb(220, 220, 220);\n"
"    background: rgb(100, 100, 100);\n"
"}")
        self.btn_load_collection.setObjectName("btn_load_collection")
        self.verticalLayout_4.addWidget(self.btn_load_collection)
        self.btn_deliver_data = QtWidgets.QPushButton(self.data_info)
        self.btn_deliver_data.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_deliver_data.setStyleSheet("QPushButton{\n"
"    color: rgb(220, 220, 220);\n"
"    background: rgb(100, 100, 100);\n"
"}")
        self.btn_deliver_data.setObjectName("btn_deliver_data")
        self.verticalLayout_4.addWidget(self.btn_deliver_data)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.data_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"background-color: rgb(80, 80, 80);\n"
"}\n"
"QGroupBox::title{\n"
"color: rgb(220, 220, 220)\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cmbx_collections = QtWidgets.QComboBox(self.groupBox_3)
        self.cmbx_collections.setStyleSheet("QComboBox{\n"
"color: rgb(220, 220, 220);\n"
"background: rgb(120, 120, 120)\n"
"}")
        self.cmbx_collections.setObjectName("cmbx_collections")
        self.verticalLayout_7.addWidget(self.cmbx_collections)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line = QtWidgets.QFrame(self.data_info)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.data_info)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lcdnum_entries = QtWidgets.QLCDNumber(self.data_info)
        self.lcdnum_entries.setStyleSheet("QFrame, QLabel, QToolTip {\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"    background: rgb(54, 54, 54);\n"
"}")
        self.lcdnum_entries.setObjectName("lcdnum_entries")
        self.horizontalLayout_8.addWidget(self.lcdnum_entries)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.line_2 = QtWidgets.QFrame(self.data_info)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.data_info)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.lcdnum_word_count = QtWidgets.QLCDNumber(self.data_info)
        self.lcdnum_word_count.setStyleSheet("QFrame, QLabel, QToolTip {\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"    background: rgb(54, 54, 54);\n"
"}")
        self.lcdnum_word_count.setDigitCount(15)
        self.lcdnum_word_count.setObjectName("lcdnum_word_count")
        self.horizontalLayout_9.addWidget(self.lcdnum_word_count)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.line_3 = QtWidgets.QFrame(self.data_info)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.btn_start_analysis = QtWidgets.QPushButton(self.data_info)
        self.btn_start_analysis.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_start_analysis.setStyleSheet("QPushButton{\n"
"    color: rgb(220, 220, 220);\n"
"    background: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QPushButton:default{\n"
"    color: rgb(220, 220, 220);\n"
"    background: rgb(100, 100, 100);\n"
"}")
        self.btn_start_analysis.setObjectName("btn_start_analysis")
        self.verticalLayout_5.addWidget(self.btn_start_analysis)
        self.line_4 = QtWidgets.QFrame(self.data_info)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.Info_layout = QtWidgets.QVBoxLayout()
        self.Info_layout.setObjectName("Info_layout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Info_layout.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.Info_layout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.data_info, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Benzaiten Data collect"))
        self.groupBox.setTitle(_translate("MainWindow", "Collected Data"))
        self.target_url_label.setText(_translate("MainWindow", "Target URL:"))
        self.target_url_label_2.setText(_translate("MainWindow", "Target collection:"))
        self.ignore_name_check.setText(_translate("MainWindow", "Ignore name check, only do this if you know what your doing!"))
        self.collection_number_label.setText(_translate("MainWindow", "Number to collect(if 0 will go until stopped:)"))
        self.add_to_data_base.setText(_translate("MainWindow", "Add to DataBase"))
        self.label.setText(_translate("MainWindow", "Page to start Collection at:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Console Log"))
        self.console_output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.chkbx_debug_mode.setText(_translate("MainWindow", "Debug Mode"))
        self.clear_output.setText(_translate("MainWindow", "Clear Output"))
        self.start_collection.setText(_translate("MainWindow", "Start collection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ingest_ctrls), _translate("MainWindow", "Ingestion controls"))
        self.btn_load_collection.setText(_translate("MainWindow", "Load collection"))
        self.btn_deliver_data.setText(_translate("MainWindow", "deliver Data Collection"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Collection to Load"))
        self.label_2.setText(_translate("MainWindow", "entries in selected data:"))
        self.label_3.setText(_translate("MainWindow", "Total Data word count:"))
        self.btn_start_analysis.setText(_translate("MainWindow", "Start Data Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data_info), _translate("MainWindow", "Data Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
